AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template que configura um bucket S3 para hospedar um website'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: live-gft-iac
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
    DeletionPolicy: Retain
Outputs:
  WebsiteURL:
    Value:
      Fn::GetAtt:
      - S3Bucket
      - WebsiteURL
    Description: URL do website hospedado no S3